# Project
project_path=modules:1.21
archives_base_name=Template
maven_group=com.beansgalaxy

# Mod
mod_name=Template
mod_author=BeansGalaxy
# When changing mod_id, you should also change:
# - Files names at `{common, fabric, forge}/src/main/resources`
# - `MOD_ID` var at `common/src/main/java/com/example/template/ExampleMod.java`mod_id=template
mod_id=template
mod_version=0.1.0
mod_description=The description of your mod. \nAccepts multilines.
mod_licence=GPL-3.0
# When changing mod_class, you should also change:
# - `ExampleMod.java` file name at `{common, fabric, forge}/src/main/java/com/example/template`
mod_class=Main
# When changing mod_group, you should also change:
# - Folder structure at `{common, fabric, forge}/src/main/java` 
mod_group=com.beansgalaxy

# Minecraft
minecraft_version=1.21
minecraft_pack_version=34

# Fabric
# https://fabricmc.net/develop
fabric_loader_version=0.16.10
fabric_api_version=0.102.0
# ModMenu: https://modrinth.com/mod/modmenu/versions
modmenu_version=11.0.3

fabric_minecraft_version_range=>=1.21
fabric_loader_version_range=>=0.16

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.0.167

neoforge_minecraft_version_range=[1.21, 1.22)
neoforge_loader_version_range=[4,)
neoforge_version_range=[21.0.167,)

# Misc
home_page=https://example.com/
#modrinth_page=https://modrinth.com/mod/example-mod
#curseforge_page=https://curseforge.com/minecraft/mc-mods/example-mod
source_page=https://github.com/author/example-mod
issues_page=https://github.com/author/example-mod/issues

# Other
# ParchmentMC: https://github.com/ParchmentMC/Parchment/tags
parchment=2024.11.10
org.gradle.jvmargs=-Xmx2G
