# Project
project_path=modules:1.20.1
archives_base_name=Template
maven_group=com.beansgalaxy

# Mod
mod_name=Template
mod_author=BeansGalaxy
# When changing mod_id, you should also change:
# - Files names at `{common, fabric, forge}/src/main/resources`
# - `MOD_ID` var at `common/src/main/java/com/example/examplemod/ExampleMod.java`mod_id=examplemod
mod_id=template
mod_version=0.1.0
mod_description=The description of your mod. \nAccepts multilines.
mod_licence=GPL-3.0
# When changing mod_class, you should also change:
# - `ExampleMod.java` file name at `{common, fabric, forge}/src/main/java/com/example/examplemod` 
mod_class=Main
# When changing mod_group, you should also change:
# - Folder structure at `{common, fabric, forge}/src/main/java` 
mod_group=com.beansgalaxy

# Minecraft
minecraft_version=1.20.1
minecraft_pack_version=18

# Fabric
# https://fabricmc.net/develop
fabric_loader_version=0.16.10
fabric_api_version=0.92.3
# ModMenu: https://modrinth.com/mod/modmenu/versions
modmenu_version=7.2.2

fabric_minecraft_version_range=>=1.20.1
fabric_loader_version_range=>=0.16

# Forge
# https://files.minecraftforge.net/
forge_version=47.3.22

forge_loader_version_range=[47,)
forge_version_range=[47,)
forge_minecraft_version_range=[1.20.1]

# Misc
home_page=https://examplemod.com/
#modrinth_page=https://modrinth.com/mod/example-mod
#curseforge_page=https://curseforge.com/minecraft/mc-mods/example-mod
source_page=https://github.com/author/example-mod
issues_page=https://github.com/author/example-mod/issues

# Other
# ParchmentMC: https://github.com/ParchmentMC/Parchment/tags
parchment=2023.09.03
org.gradle.jvmargs=-Xmx2G
